version: "3"

services:
  postgres:
    container_name: postgres_quarkus_testcontainers
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"